# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file and other cloudbuild.yaml files are used to ensure that
# our public Docker images such as gcr.io/google-samples/hello-app:1.0
# are rebuilt and updated upon changes to the repository.

steps:

# Build hello-app:1.0.
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/google-samples/hello-app:1.0'
    - '-t'
    - 'us-docker.pkg.dev/google-samples/containers/gke/hello-app:1.0'
    - '.'
  dir: 'hello-app'

# Create back-up of main.go and replace "Version: 1.0.0" with "Version: 2.0.0".
- name: 'bash'
  args:
    - '-c'
    - 'cp -p hello-app/main.go hello-app/main.go.bak && sed "s/Version: 1.0.0/Version: 2.0.0/g" hello-app/main.go.bak > hello-app/main.go'

# Build hello-app:2.0.
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/google-samples/hello-app:2.0'
    - '-t'
    - 'us-docker.pkg.dev/google-samples/containers/gke/hello-app:2.0'
    - '.'
  dir: 'hello-app'

# Push images.
images:
  - 'gcr.io/google-samples/hello-app:1.0'
  - 'us-docker.pkg.dev/google-samples/containers/gke/hello-app:1.0'
  - 'gcr.io/google-samples/hello-app:2.0'
  - 'us-docker.pkg.dev/google-samples/containers/gke/hello-app:2.0'
