
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# [START container_helloapp_skaffold]
# [START gke_kubernetes_engine_samples_hello_app_skaffold_config]
apiVersion: skaffold/v2beta4
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - context: .
    image: hello-app
deploy:
  kubectl:
    manifests:
    - manifests/helloweb-deployment.yaml
    - manifests/helloweb-service-load-balancer.yaml
# profiles:
# - name: cloudbuild
#   build:
#     googleCloudBuild: {}
# [END gke_kubernetes_engine_samples_hello_app_skaffold_config]
# [END container_helloapp_skaffold]
---
